### ISSUE TITLE
Volume support

### ISSUE THREAD

**Issue by it-aperam** [marcelo-ochoa/pgadmin4-docker-extension#24]
Having the capability to define a volume, as docker permit it (so detached or on host filesystem).

**Comment by marcelo-ochoa** [comment]
Actually there is docker volumen attached to PGAdmin named: 
   **_mochoa_pgadmin4-docker-extension-desktop-extension_pgadmin_data_**
<img width="1214" alt="image" src="https://github.com/marcelo-ochoa/pgadmin4-docker-extension/assets/16995718/a45f74ba-4be1-4f0d-981c-2e2f8ba8b56a">
It will persist across Docker Desktop Extension upgrades.
On Mac you could see the definition at: 
  $HOME/Library/Containers/com.docker.docker/Data/extensions/mochoa_pgadmin4-docker-extension/vm/docker-compose.yml
```
    volumes:
    - type: volume
      source: pgadmin_data
      target: /var/lib/pgadmin
      volume: {}
```
   Marcelo.
